allowBuilds:
  '@prisma/engines': true
  esbuild: true
  opencc: true
  prisma: true
  sharp: true
  vue-demi: true
  workerd: true
onlyBuiltDependencies:
  - '@prisma/engines'
  - prisma
  - vue-demi
  - workerd
